### PR TITLE
Add repository archival message to README

### PR DESCRIPTION
**Pull request by alanking**
Turns out, this is not a Markdown file...

### CODE REVIEW

**Comment by alanking** [comment]
I believe this is the last thing needed for https://github.com/irods/irods_resource_plugin_s3/issues/2138

**Review by korydraughn — APPROVED** [review]
Let's pound it.

**Comment by korydraughn** [comment]
Unless @trel has more words. Feel free to wait for his approval.

**Comment by alanking** [comment]
Okay. Should I link this to https://github.com/irods/irods_resource_plugin_s3/issues/2138 or just leave it?

**Comment by trel** [comment]
i like it - please point to the issue in the commit message, yes.

**Comment by korydraughn** [comment]
Seems this is ready for merging?

**Comment by alanking** [comment]
Yep, mergin...

**Pull request merged**
