### PR TITLE
[20] added support for x-amz-storage-class

### PR DESCRIPTION
**Pull request by JustinKyleJames**

### CODE REVIEW

**Review by alanking — APPROVED** [review]
Looks good to me...

Should we hold off on merging this until the accompanying plugin PR is merged?

**Comment by trel** [comment]
> Should we hold off on merging this until the accompanying plugin PR is merged? 

no?

the plugin PR uses this - and the PR will need to update to use this new SHA accordingly...

**Comment by alanking** [comment]
Okay. Y'know, just in case something in the other review caused more revisions over here was what I had in mind. But I don't see that happening. Let's add #'s, then!

**Comment by alanking** [comment]
Please # em, @JustinKyleJames. Thanks

**Comment by JustinKyleJames** [comment]
> Please # em, @JustinKyleJames. Thanks

Done

**Pull request merged**
